[package]
name = "rust-renderer-vk"
version = "0.1.0"
edition = "2018"

[dependencies]
ash="0.33.3"
winit = "0.25.0"
winapi = "0.3.9"
num = "0.4.0"
memoffset = "0.6"

[build-dependencies]
shaderc="0.7.3"
walkdir="2.3.2"