[package]
name = "rust-renderer-vk"
version = "0.1.0"
edition = "2018"

[dependencies]
ash="0.33.3"
winit = "0.26.1"
winapi = "0.3.9"
num = "0.4.0"
memoffset = "0.6"
cgmath = "0.18.0"
image = "0.24.5"

[build-dependencies]
shaderc="0.7.3"
walkdir="2.3.2"
